monitors:
  # HTTP/HTTPS Monitor
  website_homepage:
    name: "Website Homepage"
    type: http
    url: "https://isaweye.ink"
    logo: "https://home.isaweye.ink/assets-I-actually-took-the-time-to-download/image.png"
    background: "https://w0.peakpx.com/wallpaper/992/25/HD-wallpaper-3d-snakes-background-with-snakes-3d-art-snakes-green-3d-snakes.jpg"
    category: "websites"
    interval: 60
    timeout: 10
    display:
      show_history: false
      show_target: false
      show_type: false
      show_response_time: true
      # Custom colors (optional)
      header_text: "#ff00ff"
      text_color: "#00ff00"
      data_color: "#ff0000"
      # Text shadow settings (optional)
      text_shadow: "2px 2px 4px rgba(0, 0, 0, 0.5)"  # horizontal-offset vertical-offset blur-radius color

  # TCP Service Monitor
  ssh_service:
    name: "SSH Service"
    type: tcp
    host: "isaweye.ink"
    port: 22
    category: "infrastructure"
    interval: 120
    display:
      show_history: true
      show_target: true
      show_type: true
      show_response_time: false

  # UDP Service Monitor
  dns_service:
    name: "DNS Service"
    type: udp
    host: "1.1.1.1"
    port: 53
    category: "infrastructure"
    interval: 300
    display:
      show_history: true
      show_target: true
      show_type: true
      show_response_time: true

  # Minecraft Server Monitor
  minecraft_server:
    name: "Minecraft Server"
    type: minecraft
    host: "mc.hypixel.net"
    port: 25565
    category: "games"
    interval: 300
    display:
      show_history: true
      show_target: true
      show_type: true
      show_response_time: true

# Categories for organizing monitors
categories:
  - name: "Websites"
    id: "websites"
    separator: true
  - name: "Infrastructure"
    id: "infrastructure"
    separator: true
  - name: "Game Servers"
    id: "games"
    separator: true
  - name: "Online Services"
    id: "services"
    separator: true
  - name: "Custom Checks"
    id: "custom"
    separator: true
